version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-server:5432/postgres
    depends_on:
    - postgres-server
  postgres-server:
    image: postgres:11.1
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=postgres
     - POSTGRES_DB=postgres